image: "scorpil/rust:stable"

test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --verbose --jobs 1 --release # Don't parallelize, so errors are more readable

