[package]
name = "dds-rs"
version = "0.2.0"
authors = ["mechaxl"]
description = "Decodes DirectDraw Surface files"
documentation = "https://docs.rs/dds-rs/"
repository = "https://gitlab.com/mechaxl/dds-rs"
keywords = ["dds", "directdraw"]
categories = ["game-engines", "multimedia::images"]
license = "LGPL-3.0"

[lib]
name = "dds"
path = "src/lib.rs"

[[bin]]
name = "dds-info"
path = "src/main.rs"

[dependencies]
clap = "2.20.1"
prettytable-rs = "0.6.6"

[dev-dependencies]
image = "0.12.2"

[[example]]
name = "convert"
path = "examples/convert/main.rs"
